FROM node:18

WORKDIR /app

COPY package*.json ./
# Install sharp for linux platform
RUN npm install --platform=linux --arch=x64 sharp
RUN npm install
RUN npm install --save-dev @types/uuid

COPY . .
RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]